name: CronBuild

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 6,16 * * *'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - run: yarn install --frozen-lockfile
      - name: build
#        TODO Enable those lines below if you use a Redis cache, you'll also need to configure GitHub Repository Secrets
#        env:
#          REDIS_HOST: ${{ secrets.REDIS_HOST }}
#          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        run: yarn build && yarn deploy
